// Code generated by sqlc. DO NOT EDIT.

package postgres

import (
	"context"
)

type Querier interface {
	CreateTodo(ctx context.Context, name string) (Todo, error)
	DeleteTodoById(ctx context.Context, id int64) error
	GetAllTodos(ctx context.Context) ([]Todo, error)
	GetTodoById(ctx context.Context, id int64) (Todo, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error)
}

var _ Querier = (*Queries)(nil)
